### ISSUE TITLE
How to prevent damage to the device by connecting the wrong power supply and GND position?

### ISSUE THREAD

**Issue by modi12jin** [Architeuthis-Flux/breadWare#4]
![Screenshot_20211221_002523_com android chrome](https://user-images.githubusercontent.com/40233017/146799811-42d9ab9b-8010-4980-88d0-19583ad703f2.jpg)

https://blog.oshpark.com/2016/11/28/bfuse-electronic-fuse-for-breadboard/

@Architeuthis-Flux

**Comment by Architeuthis-Flux** [comment]
That’s a solid idea. I think we can take care of a few things at the same time if we have a good system to monitor current separately on as many lines as possible coming from the special function crosspoint switches. But also we cant assume people won’t use any physical jumpers. 

There also might be some clever way to do that in the analog domain; especially because the power supplies are actually op amps. Like a zener diode in parallel with a current sense resistor going to the the inverting input or something like that.

**Comment by ppeetteerrs** [comment]
I think a load switch like TPS22993 might be a potential solution to your power line and ground issue? You can also use them together with a power mux like TPS2116 to save the number of chips need.
